return {
	"onsails/lspkind-nvim",
	lazy = true,
	config = function()
    require("lspkind").init({
      mode = "symbol",
      preset = "codicons",
      symbol_map = {
        Text = "🖹",
        Method = "",
        Function = "󰊕",
        Constructor = "",
        Field = "",
        Variable = "",
        Class = "",
        Interface = "",
        Module = "",
        Property = "",
        Unit = "#",
        Value = "V",
        Enum = "",
        Keyword = "",
        Snippet = "",
        Color = "",
        File = "",
        Reference = "",
        Folder = "",
        EnumMember = "",
        Constant = "",
        Struct = "",
        Event = "",
        Operator = "",
        TypeParameter = "",
      },
    })
	end,
}
